title: devlopr
subtitle: A Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://cechmanek.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Justin Cechmanek
author_bio: Hi! Call me Justin. I'm an artificial intelligence software engineer. I build computer vision libraries for robots.
author_email: "gj.cechmanek@gmail.com"
author_location: Seattle, Washington, USA
author_website_url: "https://cechmanek.github.io"
typewrite-text: Check out some of my projects.

author_work_experiences:
            - company_name: Venmo
              company_logo: venmo_logo.jpg
              company_url: https://venmo.com
              designation: Staff Applied Scientist 
              description: It's top secret 
              visibility: true
            - company_name: Bright Machines
              company_logo: bright_machines_logo.png
              company_url: https://brightmachines.com
              designation: Senior Applied Scientist
              description: Brought deep neural networks to manufactoring automation
              visibility: true
            - company_name: Piaggio Fast Forward
              company_logo: piaggio_fast_forward_logo.png
              company_url: https://piaggiofastforward.com
              designation: Computer Vision Engineer 
              description: Made robots play nice with people 
              visibility: true
            - company_name: Dephy
              company_logo: dephy_logo.jpg
              company_url: https://dephy.com
              designation: Lead Software & Controls Engineer 
              description: Designed wearable exoskeletons to enhance human mobility
              visibility: true

author_education_details:
              - college_logo: waterloo_logo.png
                college_name: University of Waterloo
                college_url: https://uwaterloo.ca
                college_degree: Mechanical & Mechatronics Engineering
                description: Masters of Applied Science 
                visibility: true
              - college_logo: ucalgary_logo.png
                college_name: University of Calgary
                college_url: https://ucalgary.ca
                college_degree: Mechanical Engineering, Mechatronics Minor
                description: Bachelors of Science 
                visibility: true
              - college_logo: ucalgary_logo.png
                college_name: University of Calgary
                college_url: https://ucalgary.ca
                college_degree: Psychology
                description: Bachelors of Arts 
                visibility: true



#author_project_details:
#              - project_thumbnail: gamershub.png
#                project_title: Gamers Hub
#                project_description: A Platform built for Gamers and Game Devs
#                project_url: https://gamershub.in
#                visibility: true
#              - project_thumbnail: hack4r.PNG
#                project_title: Hack4r
#                project_description: A Platform built for Hackers and Penetration Testers
#                project_url: https://hack4r.com
#                visibility: true

# social links
# twitter_username: johndoe
github_username:  cechmanek
# facebook_username: johndoe
linkedin_username: Grant Justin Cechmanek
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: cechmanek

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - .well-known

destination: ./build
